# Simple perplexity evaluation configuration
defaults:
  - _self_
  - logger: wandb_disabled
  - model: gemma_2_2b
  - datasets: slimpajama
  - causal_eval: all_js

# Global
seed: 42
experiment_name: simple_perplexity_evaluation