# Evaluation configuration
defaults:
  - _self_
  - logger: wandb_disabled
  - model: gemma_2_2b
  - sae: residual_stream

# Global
seed: 42
experiment_name: eval_transport_operators


# Evaluation parameters
eval:
  # List of layers to evaluate
  Ls: [0]
  
  # List of k values (layer offsets)
  ks: [1, 2, 3]
  
  # List of j_policy values
  j_policy: ["j==i"]
  
  # Decoder configuration
  decoders:
    normalize: true
    device: auto
  
  # Scoring configuration
  scoring:
    include_residual_metrics: true
  
  val_batch_size: 128

activation_dir: ./activations-gemma2-2b-slimpajama-500k
activation_dtype: float16
