# Configuration for explain_features.py
defaults:
  - _self_


sae_layer: 1
sae_path: ${sae_layer}-gemmascope-res-16k

# Feature IDs configuration
# Either specify a JSON file containing a list of feature IDs:
feature_ids_file: "./feature_ids/feature_scores_${sae_layer}.json"  # Path to JSON file with list of feature IDs, e.g., "feature_ids.json"

# Cache directory for downloaded explanation files
cache_dir: "./explanations_dict_cache"

# Output file to save explanations (optional)
output_file: "./feature_explanations/feature_explanations_${sae_layer}.json"

# Experiment name
experiment_name: "explain_features"
