# Gemma Scope MLP SAEs
# release will be templated by model size
release_template: google/gemma-scope-${model.size}-pt-mlp

# Parameterized SAE selection
layer: 20
width: 16k  # valid examples: 16k, 65k

# Build the HF path id from parameters
id: layer_${layer}/width_${width}/canonical

# Device preference: auto | cuda | mps | cpu
device: auto
# Force redownload from HF
force_download: false
